第4回課題報告
masahiro1536/RaiseTech pull request #3
Opened 2024-02-14 13:30 UTC by masahiro1536

お世話になっております。

このプルリクエストでは、以下の主要な変更を行いました：
- 第4回課題のpngファイルをimages/lecture04フォルダに追加しました。
- 新しいlecture04.mdファイルをプロジェクトに追加し、第4回課題報告を説明しています。
- プロジェクト整理の一環として、第3回課題の写真をimages/lecture03フォルダに移動しました。この変更により、ファイル構成がより整然とし、各レクチャーの資料を見つけやすくしました。

以上、ご確認よろしくお願いいたします！

2024-02-14 14:28 UTC, MasatoshiMizumoto requested changes
コメント入れましたのでご対応お願いします！！

2024-02-14 14:28 UTC, MasatoshiMizumoto commented on lecture04.md
> +**1.VPC新規作成**
この部分のスタイリングは見出し2にしたほうが良さそうです！

2024-02-15 10:26 UTC, masahiro1536 commented on lecture04.md
> +**1.VPC新規作成**
修正行いました！
対応正しいでしょうか？

2024-02-15 13:29 UTC, MasatoshiMizumoto requested changes
よろしくお願いいたします！

2024-02-15 13:29 UTC, MasatoshiMizumoto commented on lecture04.md
> +**1.VPC新規作成**
うーん、違いますね！
段落は段落でしかないので、見出しのように使いたいなら見出しにしてください！

2024-02-15 14:17 UTC, masahiro1536 commented
対応いたしました！
軌道修正できてますか？

2024-02-15 14:22 UTC, MasatoshiMizumoto approved these changes
LGTMです！

2024-02-15 14:29 UTC, merged